### ISSUE TITLE
No Horizontal Scroll Bar

### ISSUE THREAD

**Issue by ThomasHineXYZ** [Niyko/Hydra-Dark-Theme-for-Adminer#7]
Hello, it's me again. 

There is no horizontal scroll bar for the select data screen

![Screenshot from 2020-07-24 03-27-33](https://user-images.githubusercontent.com/6890628/88382670-c9d42e80-cd5d-11ea-867f-4decefe7426f.png)

**Comment by Niyko** [comment]
I can't replicate this issue, For me scroll bars visible. Are you using the updated `adminer.css` code?
Here is a screenshot where all bars are visible (Taken in Chrome)
Anyways, Thanks for reporting. Pls try to reply back. If this issue is there, So I can fix it.
![image](https://user-images.githubusercontent.com/55660214/88824653-40e94700-d1e4-11ea-8891-3440e1ab7dff.png)

**Comment by ThomasHineXYZ** [comment]
Just updated and it seems like it's fixed. Weird, but thank you.
